<?php
/**
 * @see Convead_Tracker_Block_Adminhtml_Notification
 */
?>

<?php if (!$this->isApiKeyIntroduced()): ?>
    <div id="convead_notification" class="notification-global notification-global-notice">
        <strong>Convead:</strong> <?php echo $this->__('The module Convead Tracker is successfully installed! Go to the module settings, and enter the API key from your account Convead. The key can be obtained on the Settings page of your Convead account, when choosing OpenCart as your shop’s CMS.') ?>
    </div>
<?php endif; ?>